/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.paesa;

public class App {
    public static void main(final String[] args) {
        final String[] lists = new String[] { "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts" };
        final Parser parser = new Parser(lists);
        parser.generate();
    }
}
